import xlwt
table=xlwt.Workbook()
sheet=table.add_sheet("sheet")
sheet.write(0,0,'STATION')
sheet.write(0,1,'STATION_NAME')
sheet.write(0,2,'ELEVATION')
sheet.write(0,3,'LATITUDE')
sheet.write(0,4,'LONGTUDE')
sheet.write(0,5,'DATA')
sheet.write(0,6,'TMAX')
sheet.write(0,7,'TMIN')
sheet.write(0,8,'TOBS')
sheet.write(0,9,'SNOW DEPTH')
sheet.write(0,10,'PRECIPATION')
table.save("D:/python/1.xls")