fileName = "bclaw0000b.img"
s = "puchikon@neople dungeon and fighterDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNF "
# s = "D...?........@.(......RK......RN..U......]W!/6+ i&!(!-*%9i&-*%9vt~v&`/))FDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNFDNF."
a = chr(0)*241
f = fileName + a

# n = ""
# for i in range(255):
#     n += chr(ord(f[i])^ord(s[i]))
# print n

c = ""
l=[3,5,17,1,29,14,64,13,40]
for i in l:
    c += chr(i)

d = "puchikon@"

n = ""
for i in range(9):
    n += chr(ord(c[i])^ord(d[i]))
print n